export default {
  INITIALIZE: "INITIALIZE",
  CREATE_DATA_REQUEST: "CREATE_DATA_REQUEST",
  CREATE_DATA_SUCCESS: "CREATE_DATA_SUCCESS",
  CREATE_DATA_FAILURE: "CREATE_DATA_FAILURE",
  FETCH_DATA_REQUEST: "FETCH_DATA_REQUEST",
  FETCH_DATA_SUCCESS: "FETCH_DATA_SUCCESS",
  FETCH_DATA_FAILURE: "FETCH_DATA_FAILURE",
};